### PR TITLE
fix: update realtime endpoint

### PR DESCRIPTION
**Pull request by hebingchang**
As school bus has been outsourced to 闵行客运, we have to migrate our data source to the service provided by NIC.

### CODE REVIEW

**Comment by zry656565** [comment]
@hebingchang I have invited you to be a collaborator of SJTU-Bus. And then you could feel free to merge this by yourself.

**Comment by zry656565** [comment]
And please consider to update date in https://github.com/zry656565/SJTU-Bus/blob/master/js/main.web.js#L37

**Comment by hebingchang** [comment]
@zry656565 The time table is out of date actually. It's a bit tricky to update as the trips to the metro station are no longer the latest `n` trips in certain day.

Anyway, I will update them when possible.

**Comment by hebingchang** [comment]
btw the circle ci failed to fetch the repository. Please check the configurations if you are available.

https://app.circleci.com/pipelines/github/zry656565/SJTU-Bus/46/workflows/81d14381-48b4-45ba-93df-0902822e8bfe/jobs/109

**Comment by zry656565** [comment]
> btw the circle ci failed to fetch the repository. Please check the configurations if you are available.
> 
> https://app.circleci.com/pipelines/github/zry656565/SJTU-Bus/46/workflows/81d14381-48b4-45ba-93df-0902822e8bfe/jobs/109

Caused by expired deploy key, it's fine now.

**Comment by zry656565** [comment]
But the pipeline was blocked by old version of eslint, I guess you could just remove the lint or upgrade it or downgrade your code to ES5. :joy:

https://app.circleci.com/pipelines/github/zry656565/SJTU-Bus/46/workflows/2937b861-0e74-428c-91d6-2007e30c3d29/jobs/116

**Comment by hebingchang** [comment]
I have downgraded to ES5 ;)

**Pull request merged**
